### ISSUE TITLE
eccodes breaks gdal

### ISSUE THREAD

**Issue by matteodefelice** [conda-forge/eccodes-feedstock#46]
Issue:
If I create an environment with both `eccodes` and `gdal` the latter does not work due to a missing reference to `libpoppler`. To replicate the error:

Create the conda environment:
`conda create -n TEST_ECCODES python=3.6 eccodes gdal`
Activate it:
`conda activate TEST_ECCODES`
And now:
`python -c "import gdal"`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/matteodefelice/miniconda2/envs/TEST_ECCODES/lib/libgdal.20.dylib
  Reason: image not found
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/matteodefelice/miniconda2/envs/TEST_ECCODES:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
clangdev                  6.0.0                 default_0    conda-forge
curl                      7.61.0               h93b3f91_0    conda-forge
eccodes                   2.7.0                         0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fontconfig                2.13.0               h074f895_3    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
gdal                      2.2.4                    py36_0    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0                        0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jasper                    1.900.1                       4    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.13.1               h470a237_0    conda-forge
kealib                    1.4.8                hfc679d8_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libcurl                   7.61.0               hf30b1f0_0  
libcxx                    6.0.0                         0    conda-forge
libdap4                   3.19.1                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.4                h390fe88_1  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libopenblas               0.2.20               hdc02c5d_7  
libpng                    1.6.34               ha92aebf_1    conda-forge
libpq                     10.3                 hf30b1f0_0  
libspatialite             4.3.0a              h3b29d86_21    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmdev                   6.0.0                 default_4    conda-forge
ncurses                   6.1                           0    conda-forge
numpy                     1.14.3           py36he6379a5_2  
numpy-base                1.14.3           py36h7ef55bc_1  
openjpeg                  2.3.0                h316dc23_3    conda-forge
openssl                   1.0.2o                        0    conda-forge
pcre                      8.42                 h378b8a2_0  
pip                       18.0                     py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.67.0               hb55ee21_0    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
python                    3.6.6                hc167b69_0  
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.0.0                   py36_0    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py36_0    conda-forge
xerces-c                  3.2.1                h5d6a6da_1    conda-forge
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h470a237_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : TEST_ECCODES
    active env location : /Users/matteodefelice/miniconda2/envs/TEST_ECCODES
            shell level : 1
       user config file : /Users/matteodefelice/.condarc
 populated config files : /Users/matteodefelice/.condarc
          conda version : 4.5.8
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /Users/matteodefelice/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/matteodefelice/miniconda2/pkgs
                          /Users/matteodefelice/.conda/pkgs
       envs directories : /Users/matteodefelice/miniconda2/envs
                          /Users/matteodefelice/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/2.7.15 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
             netrc file : /Users/matteodefelice/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
This should work now with #47
